/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifba.saj;

import br.edu.ifba.saj.sistemabanco.agencia.Agencia;
import br.edu.ifba.saj.sistemabanco.cliente.Cliente;
import br.edu.ifba.saj.sistemabanco.funcionario.Funcionario;
import br.edu.ifba.saj.sistemabanco.veiculo.Veiculo;
import br.edu.ifba.saj.sistembanco.servico.Emprestimo;
import br.edu.ifba.saj.sistembanco.servico.SeguroDeVeiculo;
import br.edu.ifba.saj.sistembanco.servico.SeguroDeVida;
import br.edu.ifba.saj.sistembanco.servico.Servico;
import java.util.Date;

/**
 *
 * @author danie
 */
public class CadastroServico extends javax.swing.JInternalFrame {

    private Agencia agencia;
    private Emprestimo emprestimo;
    private SeguroDeVeiculo seguroDeVeiculo;
    private SeguroDeVida seguroDeVida;
    private Cliente cliente;

    /**
     * Creates new form CadastroServico
     */
    public CadastroServico(Agencia agencia, Emprestimo emprestimo, SeguroDeVeiculo seguroDeVeiculo, SeguroDeVida seguroDeVida) {
        this.agencia = agencia;
        this.emprestimo = emprestimo;
        this.seguroDeVeiculo = seguroDeVeiculo;
        this.seguroDeVida = seguroDeVida;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNomeFunc = new javax.swing.JTextField();
        lblNomeFunc = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        lblCPF = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        lblNomeCliente = new javax.swing.JLabel();
        cbmTipo = new javax.swing.JComboBox<>();
        txtValor = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JTextField();
        txtValorSeguro = new javax.swing.JTextField();
        lblValor = new javax.swing.JLabel();
        lblTaxa = new javax.swing.JLabel();
        lblEmprestimo = new javax.swing.JLabel();
        txtTaxa = new javax.swing.JTextField();
        lblVeiculo = new javax.swing.JLabel();
        lblPlaca = new javax.swing.JLabel();
        lblValorSeguro = new javax.swing.JLabel();
        lblFranquia = new javax.swing.JLabel();
        txtFranquia = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();

        lblNomeFunc.setText("Nome Funcionário");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblCPF.setText("CPF(Cliente Cadastrado)");

        txtCPF.setToolTipText("Informar o Nome");

        cbmTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Emprestimo", "SeguroDoVeiculo", "SeguroDeVida", " " }));

        lblValor.setText("Valor");

        lblTaxa.setText("Taxa");

        lblEmprestimo.setText("Emprestimo");

        lblVeiculo.setText("Veículo");

        lblPlaca.setText("Placa");

        lblValorSeguro.setText("Valor do Seguro");

        lblFranquia.setText("Franquia");

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblCPF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCPF))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNomeFunc)
                                .addGap(18, 18, 18)
                                .addComponent(txtNomeFunc))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblTaxa)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtTaxa, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblValor)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(135, 135, 135)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblFranquia)
                                            .addComponent(lblValorSeguro)
                                            .addComponent(lblPlaca))
                                        .addGap(16, 16, 16))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(lblEmprestimo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblVeiculo)
                                    .addComponent(txtPlaca)
                                    .addComponent(txtValorSeguro, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtFranquia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbmTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(201, 201, 201)
                                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(225, 225, 225)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeFunc)
                    .addComponent(txtNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPF)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbmTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmprestimo)
                    .addComponent(lblVeiculo))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTaxa)
                            .addComponent(txtTaxa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValorSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValorSeguro)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPlaca)
                        .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFranquia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFranquia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnOk)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        this.cliente = agencia.obterClientePorCPF(txtCPF.getText());
        //lblNome.setText(this.cliente.getNome());
        lblNomeCliente.setText(agencia.obterClientePorCPF(txtCPF.getText()).getNome());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:

        Veiculo veiculo = null;
        Funcionario funcionario = new Funcionario(txtNomeFunc.getText());
        Date data = new Date();
        if (cbmTipo.getSelectedItem().equals("Emprestimo")) {
            emprestimo.adicionarResponsavel(funcionario);
            emprestimo.adicionarContratante(cliente);
            emprestimo.adicionarData(data);
            emprestimo.setValor(Double.parseDouble(txtValor.getText()));
            emprestimo.setTaxa(Double.parseDouble(txtTaxa.getText()));
        } else if (cbmTipo.getSelectedItem().equals("SeguroDoVeiculo")) {
            seguroDeVeiculo.adicionarResponsavel(funcionario);
            seguroDeVeiculo.adicionarContratante(cliente);
            seguroDeVeiculo.adicionarData(data);
            veiculo = new Veiculo(txtPlaca.getText());
            seguroDeVeiculo.setVeiculo(veiculo);
            seguroDeVeiculo.setFranquia(Double.parseDouble(txtFranquia.getText()));
            seguroDeVeiculo.setValorDoSeguroDeVeiculo(Double.parseDouble(txtValorSeguro.getText()));
        } else {
            seguroDeVida.adicionarResponsavel(funcionario);
            seguroDeVida.adicionarContratante(cliente);
            seguroDeVida.adicionarData(data);
        }
        txtCPF.setText("");
        txtFranquia.setText("");
        txtNomeFunc.setText("");
        txtPlaca.setText("");
        txtTaxa.setText("");
        txtValor.setText("");
        txtValorSeguro.setText("");
        lblNomeCliente.setText("");

    }//GEN-LAST:event_btnOkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox<String> cbmTipo;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblEmprestimo;
    private javax.swing.JLabel lblFranquia;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblNomeFunc;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblTaxa;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblValorSeguro;
    private javax.swing.JLabel lblVeiculo;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtFranquia;
    private javax.swing.JTextField txtNomeFunc;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtTaxa;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtValorSeguro;
    // End of variables declaration//GEN-END:variables
}
