/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifba.saj;

import br.edu.ifba.saj.sistemabanco.agencia.Agencia;
import br.edu.ifba.saj.sistembanco.servico.Emprestimo;
import br.edu.ifba.saj.sistembanco.servico.SeguroDeVeiculo;
import br.edu.ifba.saj.sistembanco.servico.SeguroDeVida;
import br.edu.ifba.saj.sistembanco.servico.Servico;
import javax.swing.JInternalFrame;

/**
 *
 * @author Operador
 */
public class NewMDIApplication extends javax.swing.JFrame {

    Agencia agencia = new Agencia(1);
    Emprestimo emprestimo = new Emprestimo();
    SeguroDeVeiculo seguroDeVeiculo = new SeguroDeVeiculo();
    SeguroDeVida seguroDeVida = new SeguroDeVida();

    /**
     * Creates new form NewMDIApplication
     */
    public NewMDIApplication() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        cadastrosMenu = new javax.swing.JMenu();
        menCadCliente = new javax.swing.JMenuItem();
        menCadConta = new javax.swing.JMenuItem();
        menCadServico = new javax.swing.JMenuItem();
        pesquisaMenu = new javax.swing.JMenu();
        menPesCliente = new javax.swing.JMenuItem();
        menPesConta = new javax.swing.JMenuItem();
        menPesServico = new javax.swing.JMenuItem();
        operacaoMenu = new javax.swing.JMenu();
        menOperacao = new javax.swing.JMenuItem();
        extratoMenu = new javax.swing.JMenu();
        menExtrato = new javax.swing.JMenuItem();
        tributavelMenu = new javax.swing.JMenu();
        menTributavel = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cadastrosMenu.setText("Cadastros");

        menCadCliente.setText("Cliente");
        menCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadClienteActionPerformed(evt);
            }
        });
        cadastrosMenu.add(menCadCliente);

        menCadConta.setText("Conta");
        menCadConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadContaActionPerformed(evt);
            }
        });
        cadastrosMenu.add(menCadConta);

        menCadServico.setText("Serviço");
        menCadServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadServicoActionPerformed(evt);
            }
        });
        cadastrosMenu.add(menCadServico);

        menuBar.add(cadastrosMenu);

        pesquisaMenu.setText("Pesquisa");

        menPesCliente.setText("Cliente");
        menPesCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menPesClienteActionPerformed(evt);
            }
        });
        pesquisaMenu.add(menPesCliente);

        menPesConta.setText("Conta");
        menPesConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menPesContaActionPerformed(evt);
            }
        });
        pesquisaMenu.add(menPesConta);

        menPesServico.setText("Serviço");
        menPesServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menPesServicoActionPerformed(evt);
            }
        });
        pesquisaMenu.add(menPesServico);

        menuBar.add(pesquisaMenu);

        operacaoMenu.setText("Operação");

        menOperacao.setText("Operação");
        menOperacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menOperacaoActionPerformed(evt);
            }
        });
        operacaoMenu.add(menOperacao);

        menuBar.add(operacaoMenu);

        extratoMenu.setText("Extrato");

        menExtrato.setText("Extrato");
        menExtrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menExtratoActionPerformed(evt);
            }
        });
        extratoMenu.add(menExtrato);

        menuBar.add(extratoMenu);

        tributavelMenu.setText("Tributavel");

        menTributavel.setText("Tributavel");
        menTributavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menTributavelActionPerformed(evt);
            }
        });
        tributavelMenu.add(menTributavel);

        menuBar.add(tributavelMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadClienteActionPerformed
        // TODO add your handling code here:
        JInternalFrame jif = new CadastroCliente(agencia);
        jif.setClosable(true);
        desktopPane.add(jif);
        jif.setVisible(true);

    }//GEN-LAST:event_menCadClienteActionPerformed

    private void menPesClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menPesClienteActionPerformed
        // TODO add your handling code here:
        JInternalFrame jif = new PesquisaCliente(agencia);
        jif.setClosable(true);
        desktopPane.add(jif);
        jif.setVisible(true);

    }//GEN-LAST:event_menPesClienteActionPerformed

    private void menCadContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadContaActionPerformed
        // TODO add your handling code here:
        JInternalFrame jif = new CadastroContas(agencia);
        jif.setClosable(true);
        desktopPane.add(jif);
        jif.setVisible(true);
    }//GEN-LAST:event_menCadContaActionPerformed

    private void menPesContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menPesContaActionPerformed
        // TODO add your handling code here:
        JInternalFrame jif = new PesquisaConta(agencia);
        jif.setClosable(true);
        desktopPane.add(jif);
        jif.setVisible(true);
    }//GEN-LAST:event_menPesContaActionPerformed

    private void menCadServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadServicoActionPerformed
        // TODO add your handling code here:
        JInternalFrame jif = new CadastroServico(agencia, emprestimo, seguroDeVeiculo, seguroDeVida);
        jif.setClosable(true);
        desktopPane.add(jif);
        jif.setVisible(true);
    }//GEN-LAST:event_menCadServicoActionPerformed

    private void menPesServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menPesServicoActionPerformed
        // TODO add your handling code here:
        JInternalFrame jif = new PesquisaServico(emprestimo, seguroDeVeiculo, seguroDeVida);
        jif.setClosable(true);
        desktopPane.add(jif);
        jif.setVisible(true);
    }//GEN-LAST:event_menPesServicoActionPerformed

    private void menOperacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menOperacaoActionPerformed
        // TODO add your handling code here:
        JInternalFrame jif = new Operacoes(agencia);
        jif.setClosable(true);
        desktopPane.add(jif);
        jif.setVisible(true);
    }//GEN-LAST:event_menOperacaoActionPerformed

    private void menExtratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menExtratoActionPerformed
        // TODO add your handling code here:
        JInternalFrame jif = new Extrato(agencia);
        jif.setClosable(true);
        desktopPane.add(jif);
        jif.setVisible(true);
    }//GEN-LAST:event_menExtratoActionPerformed

    private void menTributavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menTributavelActionPerformed
        // TODO add your handling code here:
        JInternalFrame jif = new Tributavel(agencia, seguroDeVida);
        jif.setClosable(true);
        desktopPane.add(jif);
        jif.setVisible(true);
    }//GEN-LAST:event_menTributavelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewMDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewMDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewMDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewMDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewMDIApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu cadastrosMenu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu extratoMenu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menCadCliente;
    private javax.swing.JMenuItem menCadConta;
    private javax.swing.JMenuItem menCadServico;
    private javax.swing.JMenuItem menExtrato;
    private javax.swing.JMenuItem menOperacao;
    private javax.swing.JMenuItem menPesCliente;
    private javax.swing.JMenuItem menPesConta;
    private javax.swing.JMenuItem menPesServico;
    private javax.swing.JMenuItem menTributavel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu operacaoMenu;
    private javax.swing.JMenu pesquisaMenu;
    private javax.swing.JMenu tributavelMenu;
    // End of variables declaration//GEN-END:variables

}
