/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifba.saj;

import br.edu.ifba.saj.sistemabanco.agencia.Agencia;
import br.edu.ifba.saj.sistembanco.servico.Emprestimo;
import br.edu.ifba.saj.sistembanco.servico.SeguroDeVeiculo;
import br.edu.ifba.saj.sistembanco.servico.SeguroDeVida;

/**
 *
 * @author danie
 */
public class PesquisaServico extends javax.swing.JInternalFrame {

    private Emprestimo emprestimo;
    private SeguroDeVeiculo seguroDeVeiculo;
    private SeguroDeVida seguroDeVida;

    /**
     * Creates new form PesquisaServico
     */
    public PesquisaServico(Emprestimo emprestimo, SeguroDeVeiculo seguroDeVeiculo, SeguroDeVida seguroDeVida) {
        this.emprestimo = emprestimo;
        this.seguroDeVeiculo = seguroDeVeiculo;
        this.seguroDeVida = seguroDeVida;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCPF = new javax.swing.JTextField();
        lblCPF = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        lblEmprestimo = new javax.swing.JLabel();
        lblSeguroVeiculo = new javax.swing.JLabel();
        lblSeguroVida = new javax.swing.JLabel();

        lblCPF.setText("CPF");

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSeguroVida, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCPF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnPesquisar)))
                        .addGap(191, 191, 191))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(65, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(lblSeguroVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(59, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPF)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisar)
                .addGap(86, 86, 86)
                .addComponent(lblEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(lblSeguroVida, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addComponent(lblSeguroVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(172, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        lblEmprestimo.setText("");
        lblSeguroVeiculo.setText("");
        lblSeguroVida.setText("");
        String numeroCPF = txtCPF.getText();
        if (!(emprestimo.obterClientePorCPF(numeroCPF).equals(""))) {
            lblEmprestimo.setText(emprestimo.obterClientePorCPF(numeroCPF));
        }
        if (!(seguroDeVeiculo.obterClientePorCPF(numeroCPF).equals(""))) {
            lblSeguroVeiculo.setText(seguroDeVeiculo.obterClientePorCPF(numeroCPF));
        }
        if (!(seguroDeVida.obterClientePorCPF(numeroCPF).equals(""))) {
            lblSeguroVida.setText(seguroDeVida.obterClientePorCPF(numeroCPF));
        }

    }//GEN-LAST:event_btnPesquisarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblEmprestimo;
    private javax.swing.JLabel lblSeguroVeiculo;
    private javax.swing.JLabel lblSeguroVida;
    private javax.swing.JTextField txtCPF;
    // End of variables declaration//GEN-END:variables
}
